include(joinpath(@__DIR__, "extension.jl"))
include(joinpath(@__DIR__, "node_bb.jl"))
include(joinpath(@__DIR__, "variable_info.jl"))
include(joinpath(@__DIR__, "functions/functions.jl"))
include(joinpath(@__DIR__, "problem_parsed.jl"))
include(joinpath(@__DIR__, "global_options.jl"))
include(joinpath(@__DIR__, "global_optimizer.jl"))
include(joinpath(@__DIR__, "optimizer.jl"))
